export interface Company {
  id: number;
  name: string;
  website: string;
  hq_city: string;
  hq_country: string;
  regions: string[];
  category: string;
  one_liner: string;
  description: string;
  sensors: string[];
  tags: string[];
  scale_hours: number | null;
  collectors: number | null;
  verification_status: string;
  proof_links: string[];
  contact_email: string;
  lat: number;
  lng: number;
}

const companies: Company[] = [
  {
    id: 1,
    name: 'Aria Research',
    website: 'https://aria.meta.com',
    hq_city: 'Menlo Park',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Lab',
    one_liner: 'Egocentric multi-modal AI research glasses by Meta',
    description: 'Project Aria develops always-on egocentric sensing glasses for AR/AI research. Captures multi-modal data including RGB, eye tracking, IMU, spatial audio, and more.',
    sensors: ['RGB', 'IMU', 'Gaze', 'Audio', 'Depth'],
    tags: ['Multi-modal', 'Robotics', 'VLA'],
    scale_hours: 10000,
    collectors: 500,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'aria@meta.com',
    lat: 37.45,
    lng: -122.18,
  },
  {
    id: 2,
    name: 'Ego4D Consortium',
    website: 'https://ego4d-data.org',
    hq_city: 'Pittsburgh',
    hq_country: 'USA',
    regions: ['Global'],
    category: 'Lab',
    one_liner: 'Massive-scale egocentric video dataset from 13 universities',
    description: 'Ego4D is a large-scale egocentric video dataset and benchmark suite collected by a consortium of 13 universities worldwide. Over 3,670 hours of daily-life activity video.',
    sensors: ['RGB', 'Audio', 'IMU', 'Gaze'],
    tags: ['Multi-modal', 'Home', 'Industrial'],
    scale_hours: 3670,
    collectors: 930,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'ego4d@fb.com',
    lat: 40.44,
    lng: -79.99,
  },
  {
    id: 3,
    name: 'EgoExo4D',
    website: 'https://ego-exo4d-data.org',
    hq_city: 'Pittsburgh',
    hq_country: 'USA',
    regions: ['Global'],
    category: 'Lab',
    one_liner: 'Simultaneous egocentric and exocentric activity capture',
    description: 'EgoExo4D captures paired ego and exo video of skilled activities. Enables research in procedure understanding, body pose, and hand-object interaction.',
    sensors: ['RGB', 'Audio', 'IMU', 'Hands'],
    tags: ['Multi-modal', 'Industrial'],
    scale_hours: 1400,
    collectors: 740,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egoexo@meta.com',
    lat: 40.46,
    lng: -79.95,
  },
  {
    id: 4,
    name: 'TeleMoMa Lab',
    website: 'https://telemoma.github.io',
    hq_city: 'Stanford',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Lab',
    one_liner: 'Teleoperation data collection for mobile manipulation',
    description: 'TeleMoMa is a modular teleoperation framework for collecting demonstration data for mobile manipulation robots using multi-modal human interfaces.',
    sensors: ['RGB', 'Depth', 'IMU', 'Hands'],
    tags: ['Robotics', 'Teleop', 'VLA'],
    scale_hours: 200,
    collectors: 30,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'telemoma@stanford.edu',
    lat: 37.43,
    lng: -122.17,
  },
  {
    id: 5,
    name: 'EPIC Kitchens',
    website: 'https://epic-kitchens.github.io',
    hq_city: 'Bristol',
    hq_country: 'UK',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Largest egocentric cooking activity dataset',
    description: 'EPIC-KITCHENS is the largest dataset in first-person vision, featuring unscripted cooking activities recorded in native kitchen environments across multiple countries.',
    sensors: ['RGB', 'Audio', 'Hands'],
    tags: ['Home', 'Multi-modal'],
    scale_hours: 100,
    collectors: 45,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'epic@bristol.ac.uk',
    lat: 51.45,
    lng: -2.59,
  },
  {
    id: 6,
    name: 'Assembly101',
    website: 'https://assembly-101.github.io',
    hq_city: 'Munich',
    hq_country: 'Germany',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Procedural assembly understanding from ego+exo views',
    description: 'Assembly101 provides multi-view egocentric and fixed-camera recordings of people assembling and disassembling take-apart toys, with fine-grained temporal annotations.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Industrial', 'Multi-modal'],
    scale_hours: 513,
    collectors: 53,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'assembly101@tum.de',
    lat: 48.14,
    lng: 11.58,
  },
  {
    id: 7,
    name: 'SenseTime Ego',
    website: 'https://sensetime.com',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia', 'Global'],
    category: 'Platform',
    one_liner: 'Large-scale egocentric data platform for embodied AI',
    description: 'SenseTime operates large-scale egocentric data collection infrastructure supporting embodied AI training across industrial and home environments in Asia.',
    sensors: ['RGB', 'Depth', 'IMU', 'Hands', 'Audio'],
    tags: ['Industrial', 'Home', 'Robotics', 'VLA'],
    scale_hours: 50000,
    collectors: 2000,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'ego@sensetime.com',
    lat: 31.23,
    lng: 121.47,
  },
  {
    id: 8,
    name: 'Surreal Robotics',
    website: 'https://surreal.stanford.edu',
    hq_city: 'Stanford',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Lab',
    one_liner: 'Scalable robot learning from human demonstrations',
    description: 'SURREAL lab develops frameworks for scalable robot learning through large-scale human demonstration collection using VR teleoperation and egocentric recording.',
    sensors: ['RGB', 'Depth', 'Hands', 'IMU'],
    tags: ['Robotics', 'Teleop', 'VLA'],
    scale_hours: 800,
    collectors: 50,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'surreal@stanford.edu',
    lat: 37.42,
    lng: -122.16,
  },
  {
    id: 9,
    name: 'HOI4D',
    website: 'https://hoi4d.github.io',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Lab',
    one_liner: '4D egocentric hand-object interaction dataset',
    description: 'HOI4D is a large-scale 4D egocentric dataset with rich annotations for category-level human-object interaction, including 2.4M RGB-D frames.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Multi-modal'],
    scale_hours: 300,
    collectors: 80,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'hoi4d@tsinghua.edu.cn',
    lat: 39.91,
    lng: 116.39,
  },
  {
    id: 10,
    name: 'EgoBody',
    website: 'https://sanweiliti.github.io/egobody',
    hq_city: 'Zurich',
    hq_country: 'Switzerland',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Egocentric 3D body capture in social interactions',
    description: 'EgoBody captures egocentric views of 3D human body poses and shapes during social interactions, enabling research in body pose estimation from head-mounted cameras.',
    sensors: ['RGB', 'Depth', 'IMU', 'Gaze'],
    tags: ['Multi-modal', 'Home'],
    scale_hours: 68,
    collectors: 36,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egobody@ethz.ch',
    lat: 47.37,
    lng: 8.55,
  },
  {
    id: 11,
    name: 'IIITH EgoProceL',
    website: 'https://iiith.ac.in',
    hq_city: 'Hyderabad',
    hq_country: 'India',
    regions: ['India', 'Asia'],
    category: 'Lab',
    one_liner: 'Egocentric procedural learning dataset from India',
    description: 'EgoProceL from IIIT Hyderabad captures egocentric procedural activity videos across various tasks, enabling key-step recognition and procedure learning research.',
    sensors: ['RGB', 'Audio'],
    tags: ['Industrial', 'Home'],
    scale_hours: 150,
    collectors: 60,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egoprocel@iiith.ac.in',
    lat: 17.39,
    lng: 78.49,
  },
  {
    id: 12,
    name: 'Nymeria (Meta)',
    website: 'https://nymeria.frl',
    hq_city: 'Menlo Park',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Lab',
    one_liner: 'Multi-modal ego body motion dataset with language',
    description: 'Nymeria captures synchronized egocentric and body-worn sensor data with natural language descriptions for full-body motion understanding and generation.',
    sensors: ['RGB', 'IMU', 'Audio', 'Depth'],
    tags: ['Multi-modal', 'VLA'],
    scale_hours: 300,
    collectors: 264,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'nymeria@meta.com',
    lat: 37.47,
    lng: -122.15,
  },
  {
    id: 13,
    name: 'IndustReal',
    website: 'https://industreal.github.io',
    hq_city: 'Seattle',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Lab',
    one_liner: 'Industrial robot assembly from human demonstrations',
    description: 'IndustReal captures industrial assembly demonstrations using egocentric and external cameras, training robots to perform real-world manufacturing tasks.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Industrial', 'Robotics', 'Teleop'],
    scale_hours: 100,
    collectors: 20,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'industreal@nvidia.com',
    lat: 47.61,
    lng: -122.33,
  },
  {
    id: 14,
    name: 'Tokyo EgoDex',
    website: 'https://egodex.ai',
    hq_city: 'Tokyo',
    hq_country: 'Japan',
    regions: ['Asia'],
    category: 'Platform',
    one_liner: 'Dexterous hand manipulation egocentric capture',
    description: 'EgoDex specializes in capturing fine-grained dexterous hand manipulation from egocentric perspectives for robotic hand training and teleoperation research.',
    sensors: ['RGB', 'Depth', 'Hands', 'IMU'],
    tags: ['Robotics', 'Teleop', 'Industrial'],
    scale_hours: 500,
    collectors: 40,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'info@egodex.ai',
    lat: 35.68,
    lng: 139.69,
  },
  {
    id: 15,
    name: 'CaptureNet India',
    website: 'https://capturenet.in',
    hq_city: 'Bangalore',
    hq_country: 'India',
    regions: ['India', 'SEA'],
    category: 'Capture network',
    one_liner: 'Distributed egocentric data collection network across India',
    description: 'CaptureNet India operates a distributed network of data collectors equipped with egocentric capture devices across major Indian cities, providing scalable data collection as a service.',
    sensors: ['RGB', 'Audio', 'IMU'],
    tags: ['Contributor network', 'Home', 'Industrial'],
    scale_hours: 15000,
    collectors: 800,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'hello@capturenet.in',
    lat: 12.97,
    lng: 77.59,
  },
  {
    id: 16,
    name: 'SEA Robotics Hub',
    website: 'https://searobotics.sg',
    hq_city: 'Singapore',
    hq_country: 'Singapore',
    regions: ['SEA', 'Asia'],
    category: 'Platform',
    one_liner: 'SE Asian egocentric robotics data marketplace',
    description: 'SEA Robotics Hub aggregates egocentric robot operation data from factories and warehouses across Southeast Asia for manipulation policy training.',
    sensors: ['RGB', 'Depth', 'IMU', 'Hands'],
    tags: ['Robotics', 'Industrial', 'VLA'],
    scale_hours: 8000,
    collectors: 350,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'data@searobotics.sg',
    lat: 1.35,
    lng: 103.82,
  },
  {
    id: 17,
    name: 'EgoVista Lab',
    website: 'https://egovista.kaist.ac.kr',
    hq_city: 'Daejeon',
    hq_country: 'South Korea',
    regions: ['Asia'],
    category: 'Lab',
    one_liner: 'Egocentric gaze-guided activity recognition',
    description: 'EgoVista at KAIST develops gaze-conditioned egocentric activity recognition systems, combining eye tracking with first-person video for human intention understanding.',
    sensors: ['RGB', 'Gaze', 'IMU'],
    tags: ['Multi-modal', 'Home'],
    scale_hours: 250,
    collectors: 70,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egovista@kaist.ac.kr',
    lat: 36.37,
    lng: 127.36,
  },
  {
    id: 18,
    name: 'Berlin Embodied AI',
    website: 'https://embodied-ai.tu-berlin.de',
    hq_city: 'Berlin',
    hq_country: 'Germany',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Embodied AI with egocentric industrial training data',
    description: 'TU Berlin Embodied AI lab captures egocentric demonstrations in factory and workshop settings for learning manipulation policies and task planning.',
    sensors: ['RGB', 'Depth', 'Hands', 'Audio'],
    tags: ['Industrial', 'Robotics', 'VLA'],
    scale_hours: 400,
    collectors: 35,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'embodied@tu-berlin.de',
    lat: 52.51,
    lng: 13.33,
  },
];

export function getAllCompanies(): Company[] {
  return [...companies].sort((a, b) => a.name.localeCompare(b.name));
}

export function getCompanyById(id: number): Company | null {
  return companies.find(c => c.id === id) ?? null;
}
