export interface Company {
  id: number;
  name: string;
  website: string;
  hq_city: string;
  hq_country: string;
  regions: string[];
  category: string;
  one_liner: string;
  description: string;
  sensors: string[];
  tags: string[];
  scale_hours: number | null;
  collectors: number | null;
  verification_status: string;
  proof_links: string[];
  contact_email: string;
  lat: number;
  lng: number;
}

const companies: Company[] = [
  {
    id: 1,
    name: 'Aria Research',
    website: 'https://aria.meta.com',
    hq_city: 'Menlo Park',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Lab',
    one_liner: 'Egocentric multi-modal AI research glasses by Meta',
    description: 'Project Aria develops always-on egocentric sensing glasses for AR/AI research. Captures multi-modal data including RGB, eye tracking, IMU, spatial audio, and more.',
    sensors: ['RGB', 'IMU', 'Gaze', 'Audio', 'Depth'],
    tags: ['Multi-modal', 'Robotics', 'VLA'],
    scale_hours: 10000,
    collectors: 500,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'aria@meta.com',
    lat: 37.45,
    lng: -122.18,
  },
  {
    id: 2,
    name: 'Ego4D Consortium',
    website: 'https://ego4d-data.org',
    hq_city: 'Pittsburgh',
    hq_country: 'USA',
    regions: ['Global'],
    category: 'Lab',
    one_liner: 'Massive-scale egocentric video dataset from 13 universities',
    description: 'Ego4D is a large-scale egocentric video dataset and benchmark suite collected by a consortium of 13 universities worldwide. Over 3,670 hours of daily-life activity video.',
    sensors: ['RGB', 'Audio', 'IMU', 'Gaze'],
    tags: ['Multi-modal', 'Home', 'Industrial'],
    scale_hours: 3670,
    collectors: 930,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'ego4d@fb.com',
    lat: 40.44,
    lng: -79.99,
  },
  {
    id: 3,
    name: 'EgoExo4D',
    website: 'https://ego-exo4d-data.org',
    hq_city: 'Pittsburgh',
    hq_country: 'USA',
    regions: ['Global'],
    category: 'Lab',
    one_liner: 'Simultaneous egocentric and exocentric activity capture',
    description: 'EgoExo4D captures paired ego and exo video of skilled activities. Enables research in procedure understanding, body pose, and hand-object interaction.',
    sensors: ['RGB', 'Audio', 'IMU', 'Hands'],
    tags: ['Multi-modal', 'Industrial'],
    scale_hours: 1400,
    collectors: 740,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egoexo@meta.com',
    lat: 40.46,
    lng: -79.95,
  },
  {
    id: 4,
    name: 'TeleMoMa Lab',
    website: 'https://telemoma.github.io',
    hq_city: 'Stanford',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Lab',
    one_liner: 'Teleoperation data collection for mobile manipulation',
    description: 'TeleMoMa is a modular teleoperation framework for collecting demonstration data for mobile manipulation robots using multi-modal human interfaces.',
    sensors: ['RGB', 'Depth', 'IMU', 'Hands'],
    tags: ['Robotics', 'Teleop', 'VLA'],
    scale_hours: 200,
    collectors: 30,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'telemoma@stanford.edu',
    lat: 37.43,
    lng: -122.17,
  },
  {
    id: 5,
    name: 'EPIC Kitchens',
    website: 'https://epic-kitchens.github.io',
    hq_city: 'Bristol',
    hq_country: 'UK',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Largest egocentric cooking activity dataset',
    description: 'EPIC-KITCHENS is the largest dataset in first-person vision, featuring unscripted cooking activities recorded in native kitchen environments across multiple countries.',
    sensors: ['RGB', 'Audio', 'Hands'],
    tags: ['Home', 'Multi-modal'],
    scale_hours: 100,
    collectors: 45,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'epic@bristol.ac.uk',
    lat: 51.45,
    lng: -2.59,
  },
  {
    id: 6,
    name: 'Assembly101',
    website: 'https://assembly-101.github.io',
    hq_city: 'Munich',
    hq_country: 'Germany',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Procedural assembly understanding from ego+exo views',
    description: 'Assembly101 provides multi-view egocentric and fixed-camera recordings of people assembling and disassembling take-apart toys, with fine-grained temporal annotations.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Industrial', 'Multi-modal'],
    scale_hours: 513,
    collectors: 53,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'assembly101@tum.de',
    lat: 48.14,
    lng: 11.58,
  },
  {
    id: 7,
    name: 'SenseTime Ego',
    website: 'https://sensetime.com',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia', 'Global'],
    category: 'Platform',
    one_liner: 'Large-scale egocentric data platform for embodied AI',
    description: 'SenseTime operates large-scale egocentric data collection infrastructure supporting embodied AI training across industrial and home environments in Asia.',
    sensors: ['RGB', 'Depth', 'IMU', 'Hands', 'Audio'],
    tags: ['Industrial', 'Home', 'Robotics', 'VLA'],
    scale_hours: 50000,
    collectors: 2000,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'ego@sensetime.com',
    lat: 31.23,
    lng: 121.47,
  },
  {
    id: 8,
    name: 'Surreal Robotics',
    website: 'https://surreal.stanford.edu',
    hq_city: 'Stanford',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Lab',
    one_liner: 'Scalable robot learning from human demonstrations',
    description: 'SURREAL lab develops frameworks for scalable robot learning through large-scale human demonstration collection using VR teleoperation and egocentric recording.',
    sensors: ['RGB', 'Depth', 'Hands', 'IMU'],
    tags: ['Robotics', 'Teleop', 'VLA'],
    scale_hours: 800,
    collectors: 50,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'surreal@stanford.edu',
    lat: 37.42,
    lng: -122.16,
  },
  {
    id: 9,
    name: 'HOI4D',
    website: 'https://hoi4d.github.io',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Lab',
    one_liner: '4D egocentric hand-object interaction dataset',
    description: 'HOI4D is a large-scale 4D egocentric dataset with rich annotations for category-level human-object interaction, including 2.4M RGB-D frames.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Multi-modal'],
    scale_hours: 300,
    collectors: 80,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'hoi4d@tsinghua.edu.cn',
    lat: 39.91,
    lng: 116.39,
  },
  {
    id: 10,
    name: 'EgoBody',
    website: 'https://sanweiliti.github.io/egobody',
    hq_city: 'Zurich',
    hq_country: 'Switzerland',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Egocentric 3D body capture in social interactions',
    description: 'EgoBody captures egocentric views of 3D human body poses and shapes during social interactions, enabling research in body pose estimation from head-mounted cameras.',
    sensors: ['RGB', 'Depth', 'IMU', 'Gaze'],
    tags: ['Multi-modal', 'Home'],
    scale_hours: 68,
    collectors: 36,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egobody@ethz.ch',
    lat: 47.37,
    lng: 8.55,
  },
  {
    id: 11,
    name: 'IIITH EgoProceL',
    website: 'https://iiith.ac.in',
    hq_city: 'Hyderabad',
    hq_country: 'India',
    regions: ['India', 'Asia'],
    category: 'Lab',
    one_liner: 'Egocentric procedural learning dataset from India',
    description: 'EgoProceL from IIIT Hyderabad captures egocentric procedural activity videos across various tasks, enabling key-step recognition and procedure learning research.',
    sensors: ['RGB', 'Audio'],
    tags: ['Industrial', 'Home'],
    scale_hours: 150,
    collectors: 60,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egoprocel@iiith.ac.in',
    lat: 17.39,
    lng: 78.49,
  },
  {
    id: 12,
    name: 'Nymeria (Meta)',
    website: 'https://nymeria.frl',
    hq_city: 'Menlo Park',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Lab',
    one_liner: 'Multi-modal ego body motion dataset with language',
    description: 'Nymeria captures synchronized egocentric and body-worn sensor data with natural language descriptions for full-body motion understanding and generation.',
    sensors: ['RGB', 'IMU', 'Audio', 'Depth'],
    tags: ['Multi-modal', 'VLA'],
    scale_hours: 300,
    collectors: 264,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'nymeria@meta.com',
    lat: 37.47,
    lng: -122.15,
  },
  {
    id: 13,
    name: 'IndustReal',
    website: 'https://industreal.github.io',
    hq_city: 'Seattle',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Lab',
    one_liner: 'Industrial robot assembly from human demonstrations',
    description: 'IndustReal captures industrial assembly demonstrations using egocentric and external cameras, training robots to perform real-world manufacturing tasks.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Industrial', 'Robotics', 'Teleop'],
    scale_hours: 100,
    collectors: 20,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'industreal@nvidia.com',
    lat: 47.61,
    lng: -122.33,
  },
  {
    id: 14,
    name: 'Tokyo EgoDex',
    website: 'https://egodex.ai',
    hq_city: 'Tokyo',
    hq_country: 'Japan',
    regions: ['Asia'],
    category: 'Platform',
    one_liner: 'Dexterous hand manipulation egocentric capture',
    description: 'EgoDex specializes in capturing fine-grained dexterous hand manipulation from egocentric perspectives for robotic hand training and teleoperation research.',
    sensors: ['RGB', 'Depth', 'Hands', 'IMU'],
    tags: ['Robotics', 'Teleop', 'Industrial'],
    scale_hours: 500,
    collectors: 40,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'info@egodex.ai',
    lat: 35.68,
    lng: 139.69,
  },
  {
    id: 15,
    name: 'CaptureNet India',
    website: 'https://capturenet.in',
    hq_city: 'Bangalore',
    hq_country: 'India',
    regions: ['India', 'SEA'],
    category: 'Capture network',
    one_liner: 'Distributed egocentric data collection network across India',
    description: 'CaptureNet India operates a distributed network of data collectors equipped with egocentric capture devices across major Indian cities, providing scalable data collection as a service.',
    sensors: ['RGB', 'Audio', 'IMU'],
    tags: ['Contributor network', 'Home', 'Industrial'],
    scale_hours: 15000,
    collectors: 800,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'hello@capturenet.in',
    lat: 12.97,
    lng: 77.59,
  },
  {
    id: 16,
    name: 'SEA Robotics Hub',
    website: 'https://searobotics.sg',
    hq_city: 'Singapore',
    hq_country: 'Singapore',
    regions: ['SEA', 'Asia'],
    category: 'Platform',
    one_liner: 'SE Asian egocentric robotics data marketplace',
    description: 'SEA Robotics Hub aggregates egocentric robot operation data from factories and warehouses across Southeast Asia for manipulation policy training.',
    sensors: ['RGB', 'Depth', 'IMU', 'Hands'],
    tags: ['Robotics', 'Industrial', 'VLA'],
    scale_hours: 8000,
    collectors: 350,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'data@searobotics.sg',
    lat: 1.35,
    lng: 103.82,
  },
  {
    id: 17,
    name: 'EgoVista Lab',
    website: 'https://egovista.kaist.ac.kr',
    hq_city: 'Daejeon',
    hq_country: 'South Korea',
    regions: ['Asia'],
    category: 'Lab',
    one_liner: 'Egocentric gaze-guided activity recognition',
    description: 'EgoVista at KAIST develops gaze-conditioned egocentric activity recognition systems, combining eye tracking with first-person video for human intention understanding.',
    sensors: ['RGB', 'Gaze', 'IMU'],
    tags: ['Multi-modal', 'Home'],
    scale_hours: 250,
    collectors: 70,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'egovista@kaist.ac.kr',
    lat: 36.37,
    lng: 127.36,
  },
  {
    id: 18,
    name: 'Berlin Embodied AI',
    website: 'https://embodied-ai.tu-berlin.de',
    hq_city: 'Berlin',
    hq_country: 'Germany',
    regions: ['Europe'],
    category: 'Lab',
    one_liner: 'Embodied AI with egocentric industrial training data',
    description: 'TU Berlin Embodied AI lab captures egocentric demonstrations in factory and workshop settings for learning manipulation policies and task planning.',
    sensors: ['RGB', 'Depth', 'Hands', 'Audio'],
    tags: ['Industrial', 'Robotics', 'VLA'],
    scale_hours: 400,
    collectors: 35,
    verification_status: 'Verified',
    proof_links: [],
    contact_email: 'embodied@tu-berlin.de',
    lat: 52.51,
    lng: 13.33,
  },
  // ── USA ──────────────────────────────────────────────
  {
    id: 19,
    name: 'Scale AI',
    website: 'https://scale.com',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Platform',
    one_liner: 'AI training data platform powering frontier models',
    description: 'Scale AI provides high-quality training data for AI applications including robotics, autonomous vehicles, and generative AI through a global network of human annotators and automated pipelines.',
    sensors: ['RGB', 'Depth', 'Lidar'],
    tags: ['Multi-modal', 'Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.78,
    lng: -122.42,
  },
  {
    id: 20,
    name: 'Build AI',
    website: 'https://build.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'AI-powered robotic assembly and construction',
    description: 'Build AI develops robotic systems for construction and manufacturing, using vision-language-action models trained on egocentric demonstration data.',
    sensors: ['RGB', 'Depth'],
    tags: ['Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.79,
    lng: -122.43,
  },
  {
    id: 21,
    name: 'Generalist AI',
    website: 'https://generalist.ai',
    hq_city: 'San Jose',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'General-purpose embodied AI agents',
    description: 'Generalist AI builds general-purpose robotic agents capable of performing diverse real-world tasks using multi-modal foundation models.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Foundation Model', 'Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.34,
    lng: -121.89,
  },
  {
    id: 22,
    name: 'Human Archive',
    website: 'https://humanarchive.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Platform',
    one_liner: 'Large-scale human activity data archival for AI',
    description: 'Human Archive captures and curates large-scale human behavior and activity datasets from egocentric perspectives for training embodied AI systems.',
    sensors: ['RGB', 'Audio', 'IMU'],
    tags: ['Multi-modal', 'Home', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.77,
    lng: -122.41,
  },
  {
    id: 23,
    name: 'Cortex AI',
    website: 'https://cortex.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Embodied intelligence for robotic manipulation',
    description: 'Cortex AI develops embodied intelligence systems that learn manipulation skills from human demonstrations captured through egocentric sensors.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'VLA', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.80,
    lng: -122.40,
  },
  {
    id: 24,
    name: 'Origami Robotics',
    website: 'https://origamirobotics.com',
    hq_city: 'Millbrae',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Soft robotic manipulation with egocentric learning',
    description: 'Origami Robotics develops soft, foldable robotic grippers that learn manipulation policies from human demonstration data captured via egocentric cameras.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Robotics', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.60,
    lng: -122.39,
  },
  {
    id: 25,
    name: 'Figure AI',
    website: 'https://figure.ai',
    hq_city: 'Sunnyvale',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Enterprise',
    one_liner: 'General-purpose humanoid robot',
    description: 'Figure AI builds the Figure 02 general-purpose humanoid robot designed for commercial deployment, using large-scale teleoperation and egocentric data to train whole-body manipulation policies.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.37,
    lng: -122.04,
  },
  {
    id: 26,
    name: 'Tesla Optimus',
    website: 'https://tesla.com/optimus',
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Enterprise',
    one_liner: 'Tesla humanoid robot program',
    description: 'Tesla Optimus is developing a general-purpose humanoid robot leveraging Tesla manufacturing scale, FSD neural networks, and large-scale teleoperation data collection.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.44,
    lng: -122.16,
  },
  {
    id: 27,
    name: 'Sensei',
    website: 'https://sensei.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Autonomous retail store sensing and analytics',
    description: 'Sensei develops autonomous store technology using egocentric and overhead sensing to track customer behavior and automate checkout in retail environments.',
    sensors: ['RGB', 'Depth'],
    tags: ['Industrial', 'Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.76,
    lng: -122.43,
  },
  {
    id: 28,
    name: 'Physical Intelligence',
    website: 'https://physicalintelligence.company',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Foundation models for robotic manipulation',
    description: 'Physical Intelligence (Pi) builds general-purpose robot foundation models trained on diverse manipulation data, enabling robots to perform a wide range of physical tasks.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'Hands'],
    tags: ['Foundation Model', 'Robotics', 'VLA', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.79,
    lng: -122.41,
  },
  {
    id: 29,
    name: '1X Technologies',
    website: 'https://1x.tech',
    hq_city: 'Sunnyvale',
    hq_country: 'USA',
    regions: ['North America', 'Europe'],
    category: 'Enterprise',
    one_liner: 'Androids for the workforce',
    description: '1X Technologies (formerly Halodi Robotics) builds bipedal androids NEO and EVE for labor applications, training embodied AI through large-scale teleoperation data collection.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Teleop'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.38,
    lng: -122.03,
  },
  {
    id: 30,
    name: 'Covariant',
    website: 'https://covariant.ai',
    hq_city: 'Emeryville',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'AI-powered robotic picking for warehouses',
    description: 'Covariant builds AI-powered robotic systems for warehouse order picking and logistics, using large-scale real-world manipulation data to train generalizable grasping policies.',
    sensors: ['RGB', 'Depth'],
    tags: ['Robotics', 'Industrial', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.83,
    lng: -122.29,
  },
  {
    id: 31,
    name: 'Sanctuary AI',
    website: 'https://sanctuary.ai',
    hq_city: 'Vancouver',
    hq_country: 'Canada',
    regions: ['North America'],
    category: 'Enterprise',
    one_liner: 'Human-like intelligence in general-purpose robots',
    description: 'Sanctuary AI builds the Phoenix humanoid robot with the Carbon dexterous hand, using teleoperation-driven data collection to train human-like manipulation capabilities.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'Hands'],
    tags: ['Humanoid', 'Robotics', 'Teleop', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 49.28,
    lng: -123.12,
  },
  {
    id: 32,
    name: 'Apptronik',
    website: 'https://apptronik.com',
    hq_city: 'Austin',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Enterprise',
    one_liner: 'General-purpose humanoid robot Apollo',
    description: 'Apptronik develops Apollo, a general-purpose humanoid robot for logistics and manufacturing, with force-controlled joints and egocentric perception for manipulation tasks.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 30.27,
    lng: -97.74,
  },
  {
    id: 33,
    name: 'Dyna Robotics',
    website: 'https://dynarobotics.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Dynamic whole-body robot control from demonstrations',
    description: 'Dyna Robotics develops dynamic whole-body control systems for robots, learning agile locomotion and manipulation from human demonstration data.',
    sensors: ['RGB', 'IMU', 'Force/Tactile'],
    tags: ['Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.77,
    lng: -122.44,
  },
  {
    id: 34,
    name: 'Mecka AI',
    website: 'https://mecka.ai',
    hq_city: 'Toronto',
    hq_country: 'Canada',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Mechatronic AI for industrial automation',
    description: 'Mecka AI builds intelligent mechatronic systems combining advanced sensing and AI-driven control for industrial automation and robotic assembly.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 43.65,
    lng: -79.38,
  },
  {
    id: 35,
    name: 'Sunday Robotics',
    website: 'https://sundayrobotics.com',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Consumer-facing home robotics with egocentric AI',
    description: 'Sunday Robotics develops consumer home robots that learn household tasks from egocentric human demonstrations and natural language instructions.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Home', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.80,
    lng: -122.42,
  },
  {
    id: 36,
    name: 'OpenAI Robotics',
    website: 'https://openai.com',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Enterprise',
    one_liner: 'OpenAI robot learning and embodied AI research',
    description: 'OpenAI Robotics division explores embodied AI, applying large language and multi-modal models to physical robot control and manipulation tasks.',
    sensors: ['RGB', 'Depth'],
    tags: ['Foundation Model', 'Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.78,
    lng: -122.40,
  },
  {
    id: 37,
    name: 'NVIDIA Physical AI',
    website: 'https://nvidia.com',
    hq_city: 'Santa Clara',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Enterprise',
    one_liner: 'GPU-accelerated physical AI and robot simulation',
    description: 'NVIDIA Physical AI division develops GPU-accelerated simulation, synthetic data generation, and foundation models for training embodied AI and robotic systems at scale.',
    sensors: ['RGB', 'Depth', 'Lidar'],
    tags: ['Simulation', 'Foundation Model', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.35,
    lng: -121.95,
  },
  {
    id: 38,
    name: 'NVIDIA Isaac GR00T',
    website: 'https://developer.nvidia.com/isaac',
    hq_city: 'Santa Clara',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Enterprise',
    one_liner: 'Humanoid robot foundation model platform',
    description: 'NVIDIA Isaac GR00T is a foundation model platform for humanoid robots, combining simulation with real-world data to enable generalist robot behaviors across manipulation and locomotion.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Foundation Model', 'Simulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.36,
    lng: -121.96,
  },
  {
    id: 39,
    name: 'Hugging Face LeRobot',
    website: 'https://github.com/huggingface/lerobot',
    hq_city: 'New York',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Research',
    one_liner: 'Open-source robot learning library and datasets',
    description: 'LeRobot by Hugging Face is an open-source library for real-world robotics, providing pre-trained models, datasets, and tools for robot learning from demonstrations.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Open Source', 'Robotics', 'VLA', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 40.71,
    lng: -74.01,
  },
  {
    id: 40,
    name: 'DexCap',
    website: 'https://dex-cap.github.io',
    hq_city: 'Stanford',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Research',
    one_liner: 'Scalable portable dexterous manipulation capture',
    description: 'DexCap from Stanford captures dexterous manipulation demonstrations using a portable hand-mounted capture system, enabling scalable data collection for dexterous robot policies.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Dexterous Manipulation', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.43,
    lng: -122.18,
  },
  {
    id: 41,
    name: 'ARCap',
    website: 'https://arcap.github.io',
    hq_city: 'Stanford',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Research',
    one_liner: 'AR-guided robot demonstration capture',
    description: 'ARCap from Stanford uses augmented reality interfaces to guide and capture human demonstrations for robot manipulation policy training.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Teleop', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.44,
    lng: -122.16,
  },
  {
    id: 42,
    name: 'EgoMimic',
    website: 'https://egomimic.github.io',
    hq_city: 'Atlanta',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Research',
    one_liner: 'Egocentric imitation learning for bimanual manipulation',
    description: 'EgoMimic from Georgia Tech enables robots to learn bimanual manipulation tasks from egocentric human demonstrations without explicit teleoperation hardware.',
    sensors: ['RGB', 'Depth', 'Hands', 'IMU'],
    tags: ['Robotics', 'VLA', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 33.75,
    lng: -84.39,
  },
  {
    id: 43,
    name: 'AR2-D2',
    website: 'https://ar2d2.github.io',
    hq_city: 'Seattle',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Research',
    one_liner: 'AR-enabled robot data collection at scale',
    description: 'AR2-D2 from UW uses augmented reality to enable scalable, low-cost robot demonstration data collection from non-expert users for manipulation policy learning.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Teleop', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 47.61,
    lng: -122.34,
  },
  {
    id: 44,
    name: 'EgoZero',
    website: 'https://egozero.github.io',
    hq_city: 'New York',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Research',
    one_liner: 'Zero-shot egocentric-to-robot policy transfer',
    description: 'EgoZero develops methods for transferring manipulation policies learned from egocentric human video to robots without paired robot demonstrations.',
    sensors: ['RGB', 'Hands'],
    tags: ['Robotics', 'VLA', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 40.72,
    lng: -74.00,
  },
  {
    id: 45,
    name: 'GIAVA',
    website: 'https://giava.github.io',
    hq_city: 'Berkeley',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Research',
    one_liner: 'Generative interaction-aware video action models',
    description: 'GIAVA from UC Berkeley develops generative models that predict action-conditioned future video frames from egocentric observations for robot planning and control.',
    sensors: ['RGB', 'Depth'],
    tags: ['Robotics', 'VLA', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.87,
    lng: -122.27,
  },
  {
    id: 46,
    name: 'DaBoss.AI',
    website: 'https://daboss.ai',
    hq_city: 'San Jose',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Robot data collection and workflow automation',
    description: 'DaBoss.AI provides tools for large-scale robot data collection, annotation, and workflow management to accelerate embodied AI training pipelines.',
    sensors: ['RGB', 'Depth'],
    tags: ['Robotics', 'Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.35,
    lng: -121.88,
  },
  {
    id: 47,
    name: 'PrismaX',
    website: 'https://prismax.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Multi-spectral egocentric data for robotics',
    description: 'PrismaX develops multi-spectral egocentric sensing hardware and data pipelines for capturing rich sensory data used in robotic perception and manipulation training.',
    sensors: ['RGB', 'Depth', 'IMU'],
    tags: ['Multi-modal', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.79,
    lng: -122.44,
  },
  {
    id: 48,
    name: 'Foxglove',
    website: 'https://foxglove.dev',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Startup',
    one_liner: 'Open-source robot data visualization platform',
    description: 'Foxglove builds an open-source observability platform for robotics, enabling teams to visualize, debug, and manage multi-modal sensor data from robot fleets.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Open Source', 'Robotics', 'Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.76,
    lng: -122.41,
  },
  {
    id: 49,
    name: 'Skild AI',
    website: 'https://skild.ai',
    hq_city: 'Pittsburgh',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Scalable robot foundation model from CMU',
    description: 'Skild AI, spun out of CMU, builds a general-purpose robot foundation model trained on massive and diverse robot interaction data for cross-embodiment generalization.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Foundation Model', 'Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 40.45,
    lng: -79.98,
  },
  {
    id: 50,
    name: 'Gather AI',
    website: 'https://gather.ai',
    hq_city: 'Pittsburgh',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Autonomous drone inventory management',
    description: 'Gather AI uses autonomous drones with egocentric cameras to perform warehouse inventory tracking, providing real-time visibility into stock levels and locations.',
    sensors: ['RGB', 'Depth', 'Lidar'],
    tags: ['Industrial', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 40.43,
    lng: -80.01,
  },
  {
    id: 51,
    name: 'Ember Robotics',
    website: 'https://emberrobotics.com',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Scalable robot learning from human video',
    description: 'Ember Robotics develops systems that learn manipulation policies from large-scale egocentric human video, bridging the gap between human demonstrations and robot execution.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'VLA', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.80,
    lng: -122.43,
  },
  {
    id: 52,
    name: 'Boston Dynamics',
    website: 'https://bostondynamics.com',
    hq_city: 'Waltham',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Enterprise',
    one_liner: 'Advanced mobile robots for industry and research',
    description: 'Boston Dynamics builds Spot, Stretch, and Atlas robots with advanced mobility and manipulation capabilities, collecting extensive operational data across industrial deployments.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU', 'Force/Tactile'],
    tags: ['Humanoid', 'Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 42.38,
    lng: -71.24,
  },
  {
    id: 53,
    name: 'Tesla Bot Collection',
    website: 'https://tesla.com/optimus',
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Enterprise',
    one_liner: 'Large-scale humanoid robot teleoperation data',
    description: 'Tesla Bot Collection refers to Tesla large-scale teleoperation and data collection operation for training the Optimus humanoid robot across factory and home environments.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Teleop', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.45,
    lng: -122.15,
  },
  {
    id: 54,
    name: 'Serve Robotics',
    website: 'https://serverobotics.com',
    hq_city: 'Los Angeles',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Autonomous sidewalk delivery robots',
    description: 'Serve Robotics operates autonomous sidewalk delivery robots equipped with multi-modal sensors, collecting large-scale urban navigation and interaction data.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 33.94,
    lng: -118.41,
  },
  {
    id: 55,
    name: 'Scout AI',
    website: 'https://scoutai.com',
    hq_city: 'Arlington',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Autonomous scouting and reconnaissance robots',
    description: 'Scout AI develops autonomous scouting robots for defense and industrial inspection, using egocentric sensing and AI navigation for unstructured environments.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 38.88,
    lng: -77.10,
  },
  // ── China ────────────────────────────────────────────
  {
    id: 56,
    name: 'Lumos',
    website: 'https://lumos.ai',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Embodied AI data infrastructure for China',
    description: 'Lumos builds data infrastructure for embodied AI in China, providing large-scale egocentric data collection, curation, and model training pipelines for robotics.',
    sensors: ['RGB', 'Depth', 'IMU'],
    tags: ['Robotics', 'VLA', 'Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 39.91,
    lng: 116.39,
  },
  {
    id: 57,
    name: 'AgiBot',
    website: 'https://agibot.com',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'AGI-driven humanoid and mobile robots',
    description: 'AgiBot develops humanoid and mobile robots driven by AGI research, using large-scale data collection and foundation models for general-purpose robotic intelligence.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 31.23,
    lng: 121.47,
  },
  {
    id: 58,
    name: 'Galbot',
    website: 'https://galbot.com',
    hq_city: 'Suzhou',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Embodied intelligence for service robots',
    description: 'Galbot builds service robots with embodied intelligence, training manipulation and navigation policies from egocentric demonstrations in home and commercial settings.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Home', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 31.30,
    lng: 120.62,
  },
  {
    id: 59,
    name: 'Fourier Intelligence',
    website: 'https://fourierintelligence.com',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia', 'Global'],
    category: 'Enterprise',
    one_liner: 'General-purpose humanoid robot GR-1',
    description: 'Fourier Intelligence develops the GR-1 general-purpose humanoid robot and rehabilitation robotics, collecting movement and manipulation data across medical and industrial applications.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 31.24,
    lng: 121.48,
  },
  {
    id: 60,
    name: 'UBTECH Robotics',
    website: 'https://ubtrobot.com',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia', 'Global'],
    category: 'Enterprise',
    one_liner: 'Humanoid robot Walker and education robotics',
    description: 'UBTECH Robotics develops the Walker humanoid robot series and educational robots, with large-scale data collection for bipedal locomotion and manipulation.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.54,
    lng: 114.06,
  },
  {
    id: 61,
    name: 'RoboScience',
    website: 'https://roboscience.cn',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Robot learning from large-scale demonstration data',
    description: 'RoboScience develops robot learning systems trained on large-scale demonstration datasets, focusing on generalizable manipulation and assembly skills.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'VLA', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.55,
    lng: 114.07,
  },
  {
    id: 62,
    name: 'Maniformer',
    website: 'https://maniformer.github.io',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Research',
    one_liner: 'Manipulation transformer from egocentric data',
    description: 'Maniformer develops transformer architectures for robot manipulation, trained on large-scale egocentric hand-object interaction data from human demonstrations.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'VLA', 'Foundation Model', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 31.22,
    lng: 121.46,
  },
  {
    id: 63,
    name: 'RealMan Robotics',
    website: 'https://realman-robotics.com',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Lightweight dexterous robotic arms',
    description: 'RealMan Robotics produces lightweight, dexterous robotic arms for research and industry, with integrated force-torque sensing and demonstration-based programming.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Robotics', 'Dexterous Manipulation', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 39.92,
    lng: 116.40,
  },
  {
    id: 64,
    name: 'X-Humanoid',
    website: 'https://x-humanoid.com',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Next-generation humanoid robot platform',
    description: 'X-Humanoid develops next-generation humanoid robots with advanced locomotion and manipulation, using sim-to-real transfer and teleoperation data collection.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Simulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 39.90,
    lng: 116.38,
  },
  {
    id: 65,
    name: 'X Square Robot',
    website: 'https://xsquarerobot.com',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Modular humanoid robots for industry',
    description: 'X Square Robot builds modular humanoid robot platforms for industrial applications, with teleoperation-driven data collection for manipulation task learning.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Humanoid', 'Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 39.93,
    lng: 116.41,
  },
  {
    id: 66,
    name: 'LimX Dynamics',
    website: 'https://limxdynamics.com',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Dynamic legged robots with reinforcement learning',
    description: 'LimX Dynamics develops bipedal and quadruped robots using reinforcement learning and sim-to-real transfer for agile locomotion in unstructured environments.',
    sensors: ['RGB', 'Depth', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Simulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.53,
    lng: 114.05,
  },
  {
    id: 67,
    name: 'Shanghai AI Lab',
    website: 'https://shlab.org.cn',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Research',
    one_liner: 'National AI lab for embodied intelligence research',
    description: 'Shanghai AI Lab conducts cutting-edge research in embodied intelligence, developing large-scale robot learning frameworks and multi-modal datasets for manipulation and navigation.',
    sensors: ['RGB', 'Depth', 'Hands', 'IMU'],
    tags: ['Foundation Model', 'Robotics', 'VLA', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 31.25,
    lng: 121.49,
  },
  {
    id: 68,
    name: 'Pengcheng Lab ARIO',
    website: 'https://pcl.ac.cn',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Research',
    one_liner: 'All-Robot Intelligence Open platform',
    description: 'Pengcheng Lab ARIO project builds an open robot intelligence platform with standardized data collection, benchmarks, and shared model training infrastructure.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Open Source', 'Robotics', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.56,
    lng: 114.08,
  },
  {
    id: 69,
    name: 'AIRSPEED CUHK',
    website: 'https://cuhk.edu.hk',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Research',
    one_liner: 'AI robotics research from CUHK Shenzhen',
    description: 'AIRSPEED lab at CUHK Shenzhen researches high-speed robotic manipulation and dexterous grasping, collecting demonstration data for contact-rich manipulation policies.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'Hands'],
    tags: ['Robotics', 'Dexterous Manipulation', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.52,
    lng: 114.07,
  },
  {
    id: 70,
    name: 'Ruiqing Robotics',
    website: 'https://ruiqingrobotics.com',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Precision manipulation robots for manufacturing',
    description: 'Ruiqing Robotics develops high-precision manipulation robots for electronics manufacturing, using demonstration learning and force-torque sensing.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Robotics', 'Industrial', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 39.89,
    lng: 116.40,
  },
  {
    id: 71,
    name: 'Daimon Robotics',
    website: 'https://daimonrobotics.com',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Intelligent mobile manipulation for logistics',
    description: 'Daimon Robotics builds mobile manipulation robots for logistics and warehouse automation, using egocentric data to train navigation and picking policies.',
    sensors: ['RGB', 'Depth', 'Lidar'],
    tags: ['Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.55,
    lng: 114.05,
  },
  {
    id: 72,
    name: 'AgileX Robotics',
    website: 'https://agilexrobotics.com',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia', 'Global'],
    category: 'Enterprise',
    one_liner: 'Mobile robot platforms for research and industry',
    description: 'AgileX Robotics develops open-platform mobile robots including the LIMO and Ranger series, widely used in robotics research and industrial applications worldwide.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Robotics', 'Open Source', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.53,
    lng: 114.08,
  },
  {
    id: 73,
    name: 'Unitree Robotics',
    website: 'https://unitree.com',
    hq_city: 'Hangzhou',
    hq_country: 'China',
    regions: ['Asia', 'Global'],
    category: 'Enterprise',
    one_liner: 'Affordable quadruped and humanoid robots',
    description: 'Unitree Robotics produces affordable legged robots including Go2 quadruped and H1/G1 humanoids, enabling large-scale locomotion and manipulation research.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 30.27,
    lng: 120.15,
  },
  {
    id: 74,
    name: 'Xense Robotics',
    website: 'https://xenserobotics.com',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Tactile sensing for robotic manipulation',
    description: 'Xense Robotics develops high-resolution tactile sensors and sensing skins for robotic hands, enabling fine-grained force feedback during dexterous manipulation.',
    sensors: ['Force/Tactile', 'RGB'],
    tags: ['Robotics', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 31.21,
    lng: 121.48,
  },
  {
    id: 75,
    name: 'Phlexsense',
    website: 'https://phlexsense.com',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Flexible tactile sensing arrays for robots',
    description: 'Phlexsense manufactures flexible, large-area tactile sensing arrays for robotic grippers and skins, providing dense contact feedback for manipulation learning.',
    sensors: ['Force/Tactile'],
    tags: ['Robotics', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.56,
    lng: 114.06,
  },
  {
    id: 76,
    name: 'LEGACT',
    website: 'https://legact.ai',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Legged robot action learning platform',
    description: 'LEGACT develops learning platforms for legged robot locomotion and manipulation, combining sim-to-real transfer with real-world demonstration data.',
    sensors: ['RGB', 'Depth', 'IMU'],
    tags: ['Robotics', 'Simulation', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.52,
    lng: 114.05,
  },
  {
    id: 77,
    name: 'Shutu Technology',
    website: 'https://shututech.com',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Robotic arm teleoperation and data collection',
    description: 'Shutu Technology provides teleoperation hardware and software for robotic arm data collection, enabling scalable demonstration gathering for manipulation policy training.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'Hands'],
    tags: ['Robotics', 'Teleop', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.54,
    lng: 114.08,
  },
  {
    id: 78,
    name: 'TARS',
    website: 'https://tarsrobot.com',
    hq_city: 'Shanghai',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Multi-task humanoid robot learning',
    description: 'TARS develops multi-task humanoid robot learning systems, training whole-body control policies from teleoperation demonstrations and simulation.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'IMU'],
    tags: ['Humanoid', 'Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 31.24,
    lng: 121.46,
  },
  // ── Global / Multi-region ───────────────────────────
  {
    id: 79,
    name: 'Lightwheel AI',
    website: 'https://lightwheel.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Synthetic data generation for physical AI',
    description: 'Lightwheel AI generates photorealistic synthetic data and simulated environments for training physical AI systems, reducing the need for real-world data collection.',
    sensors: ['RGB', 'Depth', 'Lidar'],
    tags: ['Simulation', 'Robotics', 'Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.77,
    lng: -122.42,
  },
  {
    id: 80,
    name: 'Genesis AI',
    website: 'https://genesis-ai.dev',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America', 'Global'],
    category: 'Startup',
    one_liner: 'Generative physics simulation for robotics',
    description: 'Genesis AI develops a generative physics simulation platform that creates diverse training environments and synthetic data for robot learning at massive scale.',
    sensors: ['RGB', 'Depth'],
    tags: ['Simulation', 'Robotics', 'Foundation Model', 'Open Source'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.78,
    lng: -122.43,
  },
  {
    id: 81,
    name: 'ZenO Robotics',
    website: 'https://zenorobotics.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Zero-to-one autonomous robot deployment',
    description: 'ZenO Robotics provides end-to-end autonomous robot deployment pipelines, from data collection through policy training to real-world execution monitoring.',
    sensors: ['RGB', 'Depth', 'IMU'],
    tags: ['Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.79,
    lng: -122.42,
  },
  {
    id: 82,
    name: 'Defined.ai',
    website: 'https://defined.ai',
    hq_city: 'Lisbon',
    hq_country: 'Portugal',
    regions: ['Europe', 'Global'],
    category: 'Platform',
    one_liner: 'AI training data marketplace for speech, NLP, and vision',
    description: 'Defined.ai operates a global AI training data marketplace with curated datasets spanning speech, NLP, computer vision, and multi-modal domains for model training.',
    sensors: ['RGB', 'Audio'],
    tags: ['Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 38.72,
    lng: -9.14,
  },
  {
    id: 83,
    name: 'Nexdata',
    website: 'https://nexdata.ai',
    hq_city: 'San Jose',
    hq_country: 'USA',
    regions: ['North America', 'Asia', 'Global'],
    category: 'Platform',
    one_liner: 'Global AI data collection and annotation services',
    description: 'Nexdata provides AI training data collection, annotation, and quality management services across multiple modalities including image, video, speech, and text.',
    sensors: ['RGB', 'Audio'],
    tags: ['Multi-modal', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.33,
    lng: -121.90,
  },
  {
    id: 84,
    name: 'Objectways',
    website: 'https://objectways.com',
    hq_city: 'San Jose',
    hq_country: 'USA',
    regions: ['North America', 'India', 'Global'],
    category: 'Platform',
    one_liner: 'Data labeling and annotation for AI training',
    description: 'Objectways provides data labeling and annotation services with global workforce, supporting computer vision, NLP, and multi-modal AI training data needs.',
    sensors: ['RGB', 'Audio'],
    tags: ['Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.36,
    lng: -121.87,
  },
  {
    id: 85,
    name: 'DDD',
    website: 'https://ddd.ai',
    hq_city: 'Phnom Penh',
    hq_country: 'Cambodia',
    regions: ['SEA', 'Asia'],
    category: 'Platform',
    one_liner: 'Impact-sourced data labeling from Southeast Asia',
    description: 'DDD (Digital Divide Data) provides impact-sourced data labeling and annotation services from Southeast Asia, supporting AI training data needs while creating economic opportunity.',
    sensors: ['RGB'],
    tags: ['Multi-modal', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 11.56,
    lng: 104.93,
  },
  {
    id: 86,
    name: 'Labellerr',
    website: 'https://labellerr.com',
    hq_city: 'Noida',
    hq_country: 'India',
    regions: ['India', 'Asia'],
    category: 'Platform',
    one_liner: 'Automated data labeling platform for computer vision',
    description: 'Labellerr provides an automated data labeling platform for computer vision and multi-modal AI, with tools for image, video, and 3D point cloud annotation.',
    sensors: ['RGB', 'Depth', 'Lidar'],
    tags: ['Multi-modal', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 28.57,
    lng: 77.32,
  },
  {
    id: 87,
    name: 'Noitom Robotics',
    website: 'https://noitom.com',
    hq_city: 'Beijing',
    hq_country: 'China',
    regions: ['Asia', 'Global'],
    category: 'Enterprise',
    one_liner: 'Inertial motion capture for robotics and entertainment',
    description: 'Noitom develops inertial motion capture systems (Perception Neuron) used in robotics teleoperation, animation, and movement analysis for training embodied AI.',
    sensors: ['Motion Capture', 'IMU'],
    tags: ['Multi-modal', 'Robotics', 'Teleop'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 39.92,
    lng: 116.38,
  },
  {
    id: 88,
    name: 'Virdyn',
    website: 'https://virdyn.com',
    hq_city: 'Shenzhen',
    hq_country: 'China',
    regions: ['Asia'],
    category: 'Startup',
    one_liner: 'Full-body motion capture gloves and suits',
    description: 'Virdyn develops wearable motion capture technology including data gloves and full-body suits for capturing human motion data used in robotics and digital human applications.',
    sensors: ['Motion Capture', 'IMU', 'Hands'],
    tags: ['Multi-modal', 'Robotics', 'Teleop'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 22.55,
    lng: 114.04,
  },
  {
    id: 89,
    name: 'Infermove',
    website: 'https://infermove.com',
    hq_city: 'Singapore',
    hq_country: 'Singapore',
    regions: ['SEA', 'Asia'],
    category: 'Startup',
    one_liner: 'Motion intelligence platform for embodied AI',
    description: 'Infermove develops a motion intelligence platform that captures and analyzes human movement data for training embodied AI agents in logistics and industrial settings.',
    sensors: ['RGB', 'Motion Capture', 'IMU'],
    tags: ['Robotics', 'Industrial', 'Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 1.35,
    lng: 103.82,
  },
  {
    id: 90,
    name: 'Echo Teleoperation',
    website: 'https://echoteleop.com',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Low-latency robot teleoperation systems',
    description: 'Echo Teleoperation builds low-latency, high-fidelity teleoperation systems enabling remote human operators to control robots and collect demonstration data at scale.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'Hands'],
    tags: ['Robotics', 'Teleop', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.76,
    lng: -122.42,
  },
  {
    id: 91,
    name: 'DOGlove',
    website: 'https://doglove.dev',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Haptic data glove for dexterous robot teleop',
    description: 'DOGlove develops haptic feedback data gloves for dexterous robot teleoperation, capturing finger-level force and motion data for training robot hand policies.',
    sensors: ['Force/Tactile', 'Motion Capture', 'Hands'],
    tags: ['Robotics', 'Teleop', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.80,
    lng: -122.41,
  },
  {
    id: 92,
    name: 'Rerun',
    website: 'https://rerun.io',
    hq_city: 'Stockholm',
    hq_country: 'Sweden',
    regions: ['Europe', 'Global'],
    category: 'Startup',
    one_liner: 'Open-source SDK for multi-modal data visualization',
    description: 'Rerun builds an open-source SDK for logging, visualizing, and analyzing multi-modal data streams from robots, autonomous vehicles, and spatial computing.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Open Source', 'Multi-modal', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 59.33,
    lng: 18.07,
  },
  {
    id: 93,
    name: 'RLWRLD',
    website: 'https://rlwrld.com',
    hq_city: 'Singapore',
    hq_country: 'Singapore',
    regions: ['SEA', 'Asia'],
    category: 'Startup',
    one_liner: 'Reinforcement learning for real-world robotics',
    description: 'RLWRLD develops reinforcement learning frameworks optimized for real-world robotic deployment, bridging sim-to-real gaps with efficient demonstration data.',
    sensors: ['RGB', 'Depth'],
    tags: ['Robotics', 'Simulation', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 1.36,
    lng: 103.83,
  },
  {
    id: 94,
    name: 'Icarus Robotics',
    website: 'https://icarusrobotics.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Aerial robot data collection and autonomy',
    description: 'Icarus Robotics develops autonomous aerial robots with egocentric sensing for inspection, mapping, and data collection in industrial and urban environments.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.77,
    lng: -122.43,
  },
  {
    id: 95,
    name: 'Houou Data Platform',
    website: 'https://houou.ai',
    hq_city: 'Tokyo',
    hq_country: 'Japan',
    regions: ['Asia'],
    category: 'Platform',
    one_liner: 'Japanese robotics data exchange platform',
    description: 'Houou Data Platform provides a centralized data exchange for Japanese robotics companies and labs to share and trade robot demonstration and operational datasets.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Multi-modal', 'Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 35.69,
    lng: 139.70,
  },
  // ── Europe ──────────────────────────────────────────
  {
    id: 96,
    name: 'Mimic Robotics',
    website: 'https://mimicrobotics.com',
    hq_city: 'Zurich',
    hq_country: 'Switzerland',
    regions: ['Europe'],
    category: 'Startup',
    one_liner: 'Learning manipulation from human mimicry',
    description: 'Mimic Robotics develops systems that learn robot manipulation through human mimicry, using egocentric capture of human hand movements to train dexterous robot policies.',
    sensors: ['RGB', 'Depth', 'Hands'],
    tags: ['Robotics', 'Dexterous Manipulation', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 47.37,
    lng: 8.54,
  },
  {
    id: 97,
    name: 'ANYbotics',
    website: 'https://anybotics.com',
    hq_city: 'Zurich',
    hq_country: 'Switzerland',
    regions: ['Europe', 'Global'],
    category: 'Enterprise',
    one_liner: 'Autonomous legged inspection robot ANYmal',
    description: 'ANYbotics builds ANYmal, an autonomous quadruped robot for industrial inspection, collecting operational data across energy, construction, and mining environments.',
    sensors: ['RGB', 'Depth', 'Lidar', 'IMU'],
    tags: ['Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 47.38,
    lng: 8.56,
  },
  {
    id: 98,
    name: 'Bota Systems',
    website: 'https://botasys.com',
    hq_city: 'Zurich',
    hq_country: 'Switzerland',
    regions: ['Europe', 'Global'],
    category: 'Startup',
    one_liner: 'Multi-axis force-torque sensors for robots',
    description: 'Bota Systems develops compact, high-performance multi-axis force-torque sensors for robotic arms, enabling precise force-controlled manipulation and contact-rich task learning.',
    sensors: ['Force/Tactile'],
    tags: ['Robotics', 'Dexterous Manipulation', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 47.39,
    lng: 8.53,
  },
  {
    id: 99,
    name: 'Partner Robotics',
    website: 'https://partnerrobotics.com',
    hq_city: 'Paris',
    hq_country: 'France',
    regions: ['Europe'],
    category: 'Startup',
    one_liner: 'Collaborative humanoid robots for industry',
    description: 'Partner Robotics develops collaborative humanoid robots for industrial applications, with teleoperation-based data collection for learning assembly and logistics tasks.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Humanoid', 'Robotics', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 48.86,
    lng: 2.35,
  },
  // ── Mocap / Sensing ─────────────────────────────────
  {
    id: 100,
    name: 'Xsens Movella',
    website: 'https://movella.com',
    hq_city: 'Enschede',
    hq_country: 'Netherlands',
    regions: ['Europe', 'Global'],
    category: 'Enterprise',
    one_liner: 'Inertial motion capture and sensor fusion technology',
    description: 'Xsens (Movella) develops inertial motion capture suits and IMU sensor modules used globally in robotics, biomechanics, and autonomous systems for human motion analysis.',
    sensors: ['Motion Capture', 'IMU'],
    tags: ['Multi-modal', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 52.22,
    lng: 6.90,
  },
  {
    id: 101,
    name: 'Rokoko',
    website: 'https://rokoko.com',
    hq_city: 'Copenhagen',
    hq_country: 'Denmark',
    regions: ['Europe', 'Global'],
    category: 'Enterprise',
    one_liner: 'Affordable full-body motion capture for all',
    description: 'Rokoko makes affordable inertial motion capture suits and gloves, democratizing human movement data capture for animation, robotics, and embodied AI training.',
    sensors: ['Motion Capture', 'IMU', 'Hands'],
    tags: ['Multi-modal', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 55.68,
    lng: 12.57,
  },
  {
    id: 102,
    name: 'Vicon',
    website: 'https://vicon.com',
    hq_city: 'Oxford',
    hq_country: 'UK',
    regions: ['Europe', 'Global'],
    category: 'Enterprise',
    one_liner: 'Gold-standard optical motion capture systems',
    description: 'Vicon produces industry-leading optical motion capture systems used in robotics research, biomechanics, VFX, and virtual production for sub-millimeter 3D tracking.',
    sensors: ['Motion Capture'],
    tags: ['Multi-modal', 'Robotics'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 51.75,
    lng: -1.25,
  },
  {
    id: 103,
    name: 'VIVE Robotics',
    website: 'https://vive.com',
    hq_city: 'Taoyuan',
    hq_country: 'Taiwan',
    regions: ['Asia'],
    category: 'Enterprise',
    one_liner: 'VR/AR tracking technology for robot teleoperation',
    description: 'VIVE Robotics applies HTC VIVE VR/AR tracking technology to robot teleoperation and data collection, providing precise 6-DOF tracking for manipulation demonstrations.',
    sensors: ['RGB', 'Motion Capture', 'Hands'],
    tags: ['Robotics', 'Teleop', 'Multi-modal'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 24.99,
    lng: 121.31,
  },
  // ── South Korea ─────────────────────────────────────
  {
    id: 104,
    name: 'OpenGraph Labs',
    website: 'https://opengraphlabs.com',
    hq_city: 'Seoul',
    hq_country: 'South Korea',
    regions: ['South Korea', 'Asia'],
    category: 'Startup',
    one_liner: 'Graph-based robot scene understanding',
    description: 'OpenGraph Labs develops graph-based scene understanding for robots, enabling structured reasoning about objects, relations, and affordances from egocentric observations.',
    sensors: ['RGB', 'Depth'],
    tags: ['Robotics', 'VLA', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.57,
    lng: 126.98,
  },
  {
    id: 105,
    name: 'FRT Robotics',
    website: 'https://frtrobotics.com',
    hq_city: 'Seoul',
    hq_country: 'South Korea',
    regions: ['South Korea', 'Asia'],
    category: 'Startup',
    one_liner: 'Force-responsive teleoperation for robot arms',
    description: 'FRT Robotics develops force-responsive teleoperation systems for robotic arms, capturing rich haptic demonstration data for contact-rich manipulation policy learning.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Robotics', 'Teleop', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.58,
    lng: 126.99,
  },
  {
    id: 106,
    name: 'ConfigIntelligence',
    website: 'https://configintelligence.com',
    hq_city: 'Seoul',
    hq_country: 'South Korea',
    regions: ['South Korea', 'Asia'],
    category: 'Startup',
    one_liner: 'Configurable robot intelligence platform',
    description: 'ConfigIntelligence builds a configurable robot intelligence platform enabling rapid deployment of learned manipulation skills across diverse robot hardware configurations.',
    sensors: ['RGB', 'Depth'],
    tags: ['Robotics', 'VLA', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.56,
    lng: 126.97,
  },
  {
    id: 107,
    name: 'Tepa Robotics',
    website: 'https://teparobotics.com',
    hq_city: 'Seoul',
    hq_country: 'South Korea',
    regions: ['South Korea', 'Asia'],
    category: 'Startup',
    one_liner: 'Telepresence and robot manipulation research',
    description: 'Tepa Robotics develops telepresence robotic systems with haptic feedback, collecting human manipulation demonstration data for training dexterous robot policies.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'Hands'],
    tags: ['Robotics', 'Teleop', 'Dexterous Manipulation'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.59,
    lng: 126.98,
  },
  {
    id: 108,
    name: 'Realworld',
    website: 'https://realworld.to',
    hq_city: 'Seoul',
    hq_country: 'South Korea',
    regions: ['South Korea', 'Asia'],
    category: 'Startup',
    one_liner: 'Real-world robot learning and deployment platform',
    description: 'Realworld builds an end-to-end platform for real-world robot learning, from demonstration collection through policy training to deployment monitoring in production environments.',
    sensors: ['RGB', 'Depth', 'IMU'],
    tags: ['Robotics', 'VLA', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 37.55,
    lng: 126.99,
  },
  // ── Japan ───────────────────────────────────────────
  {
    id: 109,
    name: 'AI Robot Association',
    website: 'https://aira.or.jp',
    hq_city: 'Tokyo',
    hq_country: 'Japan',
    regions: ['Asia'],
    category: 'Research',
    one_liner: 'Japanese industry consortium for robot AI standards',
    description: 'AI Robot Association is a Japanese industry consortium promoting standardized robot data formats, shared benchmarks, and collaborative embodied AI research across member organizations.',
    sensors: ['RGB', 'Depth', 'Force/Tactile'],
    tags: ['Robotics', 'Open Source', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 35.68,
    lng: 139.68,
  },
  // ── New Additions (Feb 2026) ──────────────────────────
  {
    id: 110,
    name: 'MicroAGI',
    website: 'https://www.microagi.ai',
    hq_city: 'Munich',
    hq_country: 'Germany',
    regions: ['Europe'],
    category: 'Startup',
    one_liner: 'Real-world egocentric data capture platform teaching robots human skills for embodied AI',
    description: 'MicroAGI builds a real-world egocentric data capture platform that teaches robots human skills for embodied AI. Focuses on household tasks and skilled trades using helmet-mounted cameras and belt-unit wearable capture devices.',
    sensors: ['RGB', 'IMU', 'Audio'],
    tags: ['Robotics', 'Home', 'Industrial', 'VLA', 'Foundation Model'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 48.14,
    lng: 11.58,
  },
  {
    id: 111,
    name: 'Train Them AI',
    website: 'https://trainthemai.com',
    hq_city: 'Córdoba',
    hq_country: 'Argentina',
    regions: ['Global'],
    category: 'Capture network',
    one_liner: 'Premium ethically-sourced video dataset collection for CV models using diverse Latin American demographics',
    description: 'Train Them AI provides premium ethically-sourced video dataset collection for Computer Vision models. Uses diverse Latin American demographics with remote collectors recording scripted scenarios via consumer smartphones.',
    sensors: ['RGB', 'Audio'],
    tags: ['Multi-modal', 'Contributor network'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: -31.42,
    lng: -64.18,
  },
  {
    id: 112,
    name: 'SentientX',
    website: 'https://www.sentientx.io',
    hq_city: 'Bangalore',
    hq_country: 'India',
    regions: ['India', 'Asia'],
    category: 'Startup',
    one_liner: 'Real-world robot training data collection via teleoperation, motion capture, and RL for robotics',
    description: 'SentientX provides real-world robot training data collection via teleoperation, motion capture, UMI grippers, and reinforcement learning for robotics deployment. Uses MyArm MC teleop kits, VR headsets (Quest/Vision Pro), optical motion capture studios, humanoid platforms, and industrial arms.',
    sensors: ['RGB', 'Depth', 'Force/Tactile', 'Motion Capture', 'IMU'],
    tags: ['Robotics', 'Teleop', 'Humanoid', 'Dexterous Manipulation', 'Industrial'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 12.98,
    lng: 77.58,
  },
  {
    id: 113,
    name: 'FPV Labs',
    website: 'https://www.fpvlabs.ai',
    hq_city: 'Bangalore',
    hq_country: 'India',
    regions: ['India', 'Asia'],
    category: 'Startup',
    one_liner: 'Foundational infrastructure for egocentric AI data powering spatial computing and physical AI',
    description: 'FPV Labs builds foundational infrastructure for egocentric (first-person view) AI data powering spatial computing and physical AI. Uses smart glasses, egocentric cameras, and first-person wearable capture devices.',
    sensors: ['RGB', 'IMU', 'Depth', 'Gaze'],
    tags: ['Multi-modal', 'Foundation Model', 'Robotics', 'VLA'],
    scale_hours: null,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: '',
    lat: 12.97,
    lng: 77.59,
  },
  {
    id: 114,
    name: 'Two Labs',
    website: 'https://www.twolabs.ai',
    hq_city: 'San Francisco',
    hq_country: 'USA',
    regions: ['North America'],
    category: 'Startup',
    one_liner: 'Egocentric video datasets from wearable cameras to train robots for physical labor',
    description: 'Two Labs deploys wearable cameras on workers across labor-intensive industries to capture POV footage of real labor, label it, and sell it to AI labs and robotics companies. Over 10K+ hours of labeled egocentric footage across agriculture, textiles, and food processing.',
    sensors: ['RGB'],
    tags: ['Robotics', 'Foundation Model'],
    scale_hours: 10000,
    collectors: null,
    verification_status: 'Unverified',
    proof_links: [],
    contact_email: 'team@twolabs.ai',
    lat: 37.78,
    lng: -122.42,
  },
];

export function getAllCompanies(): Company[] {
  return [...companies].sort((a, b) => a.name.localeCompare(b.name));
}

export function getCompanyById(id: number): Company | null {
  return companies.find(c => c.id === id) ?? null;
}
